[package]
name = "native-executor"
version = "0.8.0"
edition = "2024"
authors = ["Lexo Liu"]
license = "MIT"
repository = "https://github.com/waterui/native-executor"
description = "Platform-native async task executor"
keywords = ["task", "async", "concurrency", "waterui"]
categories = ["asynchronous", "concurrency"]

[dependencies]
async-task = { version = "4.7.1"}
libc = "0.2"


[target.'cfg(target_vendor = "apple")'.dependencies]
block2 = "0.6"

[target.'cfg(target_os = "android")'.dependencies]
ndk-sys = "0.6"
async-io = "2.6.0"
executor-core = { version = "0.7.0" , features = ["async-task", "async-executor"] }
jni = "0.21"
ndk = "0.9"
thiserror = "2.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
executor-core = { version = "0.7.0" , features = ["async-task"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-executor = { version = "1.13.3", optional = true }
num_cpus = { version = "1.17.0", optional = true}
futures-lite = { version = "2.6.1", optional = true}
async-io = { version = "2.6.0", optional = true}


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
js-sys = "0.3"

[dev-dependencies]
futures-lite = "2.6.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["polyfill"]
polyfill = ["dep:async-executor","dep:num_cpus", "dep:futures-lite","dep:async-io"]


[lints]
rust.missing_debug_implementations = "warn"
clippy.all = "warn"
clippy.style = "warn"
clippy.correctness = "warn"
clippy.complexity = "warn"
clippy.suspicious = "warn"
clippy.perf = "warn"
clippy.pedantic = "warn"
clippy.nursery = "warn"
